name: dashboy
description: dashboy

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^4.1.3
  json_annotation: ^4.3.0
  flutter_hooks: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.0

flutter:

  uses-material-design: true
